services:
  app-local:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/choresdatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: America/Chicago
    depends_on:
      - db
    profiles:
      - local

  app-rds:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: America/Chicago
    profiles:
      - rds

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: choresdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database_backup_latest.sql:/docker-entrypoint-initdb.d/database_backup_latest.sql
    profiles:
      - local

volumes:
  pgdata: