CREATE TABLE public.chores (
    name character varying(255),
    description character varying(255),
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date
);

CREATE TABLE public.chores_import (
    date date NOT NULL,
    name text NOT NULL,
    description text NOT NULL
);

CREATE TABLE public.names (
    name character varying(255),
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountassociated boolean DEFAULT false
);

CREATE TABLE public.names_import (
    name text NOT NULL
);

CREATE TABLE public.users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled boolean NOT NULL,
    expopushtoken character varying(255),
    fullname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    reminder_time time(6) without time zone,
    username character varying(255) NOT NULL
);